name: 🚀 Deploy NestJS Clinica Psiquiatrica API to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Parse Connection Variables
      id: parse_vars
      run: |
        # Extraer de forma limpia la IP y el Usuario desde tu secret VARIABLES_AX
        HOST=$(echo "${{ secrets.VARIABLES_AX }}" | grep '^VPS_HOST=' | cut -d'=' -f2 | tr -d '\r ')
        USER=$(echo "${{ secrets.VARIABLES_AX }}" | grep '^VPS_USER=' | cut -d'=' -f2 | tr -d '\r ')
        
        echo "vps_host=$HOST" >> $GITHUB_OUTPUT
        echo "vps_user=$USER" >> $GITHUB_OUTPUT

    - name: Copy project files to VPS via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ steps.parse_vars.outputs.vps_host }}
        username: ${{ steps.parse_vars.outputs.vps_user }}
        key: ${{ secrets.VPS_KEY }}
        source: "."
        target: "/var/www/clinica-psiquiatrica-api"

    - name: Executing remote SSH commands to deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ steps.parse_vars.outputs.vps_host }}
        username: ${{ steps.parse_vars.outputs.vps_user }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          set -e
          cd /var/www/clinica-psiquiatrica-api
          
          # Filtra las variables exclusivas de la App para armar el .env limpio sin las de VPS
          echo "${{ secrets.VARIABLES_AX }}" | grep -v '^VPS_' > .env

          # Instalar dependencias y compilar
          npm install
          npm run build

          # Reinicio en PM2
          pm2 reload clinica-api || pm2 start dist/main.js --name "clinica-api"
          pm2 save
